[programs.localnet]
atlasfarm = "648s29idGPQ5mJ8fSgCQZudQYBXXrYjLva8aaAdf2795"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
