[programs.localnet]
atlas_farming = "DEXqAUczH6bFWfJ5ePjRmkJkAWj9ocE27pMKvYGyNKAD"

[programs.devnet]
atlas_farming = "DEXqAUczH6bFWfJ5ePjRmkJkAWj9ocE27pMKvYGyNKAD"

[programs.testnet]
atlas_farming = "DEXqAUczH6bFWfJ5ePjRmkJkAWj9ocE27pMKvYGyNKAD"

[programs.mainnet]
atlas_farming = "DEXqAUczH6bFWfJ5ePjRmkJkAWj9ocE27pMKvYGyNKAD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./wallet.json"

[scripts]
test = "mocha -t 1000000 tests/"